import {
  IconBrandFacebook,
  IconBrandInstagramFilled,
  IconBrandLinkedinFilled,
  IconBrandPinterestFilled,
  IconBrandTiktok,
  IconBrandX,
  IconBrandYoutubeFilled,
  IconFileFilled,
  IconFolder,
  IconFolderFilled,
  IconHome,
  IconHomeFilled,
  IconPhotoFilled,
  IconPresentationFilled,
  IconSettings,
  IconSortDescendingShapesFilled,
  IconSparkles,
  IconTable,
  IconTableFilled
} from "@tabler/icons-react";

export const workspaceMenuItems = [
  {
    name: "Home",
    icon: IconHome,
    iconFilled: IconHomeFilled,
    path: "/workspace",
  },
  {
    name: "Projects",
    icon: IconFolder,
    iconFilled: IconFolderFilled,
    path: "/workspace/projects",
  },
  {
    name: "Templates",
    icon: IconTable,
    iconFilled: IconTableFilled,
    path: "/workspace/templates",
  },
  {
    name: "Cavna AI",
    icon: IconSparkles,
    iconFilled: IconSparkles,
    path: "/workspace/ai",
  },
  {
    name: "Admin",
    icon: IconSettings,
    iconFilled: IconSettings,
    path: "/workspace/settings",
  },
];

export const canvasSizeOptions = [
  {
    name: "Logo",
    width: 500,
    height: 500,
    icon: IconSortDescendingShapesFilled,
    color: "#6453d0",
    background: "#f2f3f5",
  },
  {
    name: "YouTube Thumbnail",
    width: 1280,
    height: 720,
    icon: IconBrandYoutubeFilled,
    color: "#e950f7",
    background: "#f2f3f5",
  },
  {
    name: "YouTube Banner",
    width: 2560,
    height: 1440,
    icon: IconBrandYoutubeFilled,
    color: "#ff3b4b",
    background: "#f2f3f5",
  },
  {
    name: "Instagram Post",
    width: 500,
    height: 500,
    icon: IconBrandInstagramFilled,
    color: "#ff339c",
    background: "#f2f3f5",
  },
  {
    name: "Photo Editor",
    width: 1080,
    height: 1920,
    icon: IconPhotoFilled,
    background: "#4a53fa",
  },
  {
    name: "TikTok Video",
    width: 1080,
    height: 1920,
    icon: IconBrandTiktok,
    background: "#000",
  },
  {
    name: "Presentation",
    width: 1920,
    height: 1080,
    icon: IconPresentationFilled,
    background: "#ff6105",
  },
  {
    name: "Flyer (A4)",
    width: 2480,
    height: 3508,
    icon: IconFileFilled,
    background: "#0ba84a",
  },
  {
    name: "Facebook Post",
    width: 940,
    height: 788,
    icon: IconBrandFacebook,
    background: "#4a53fa",
  },
  {
    name: "Twitter Post",
    width: 1600,
    height: 900,
    icon: IconBrandX,
    background: "#000000",
  },
  {
    name: "LinkedIn Cover Photo",
    width: 1584,
    height: 396,
    icon: IconBrandLinkedinFilled,
    background: "#138eff",
  },
  {
    name: "Pinterest Pin",
    width: 1000,
    height: 1500,
    icon: IconBrandPinterestFilled,
    color: "#E60023",
    background: "#f2f3f5",
  },
];
